---
  - name: create file
    hosts: all
    tasks:
      - name: create file
        my_own_namespace.yandex_cloud_elk.my_own_module:
          path: /tmp/2/second_file
          content: New content in new file